random_state: 123
n_rounds: 1000
n_unique_action: 5
len_list: 5
dim_context: 5
behavior_policy_function: linear
reward_type: binary
reward_structure: cascade
click_model: cascade
is_factorizable: true
eta: 0.0
lambda_: 0.4
interaction_function: additive
n_random_state: 10
decay_function: inverse
behavior_policy: linear